Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job stats:
job                    count
-------------------  -------
all                        1
plot_sofia_products        1
total                      2

Select jobs to execute...

[Sun Dec 31 21:28:09 2023]
rule plot_sofia_products:
    input: data/hcg30/optical/legacystamps_69.152500_-3.186400_ls-dr10-gfilter.fits, data/hcg30/optical/legacystamps_69.152500_-3.186400_ls-dr10-rfilter.fits, data/hcg30/optical/legacystamps_69.152500_-3.186400_ls-dr10-ifilter.fits, results/sofia_pbc/hcg30/hcg30_line60_masked.pb_corr_vopt_cubelets/hcg30_line60_masked.pb_corr_vopt_1_mom0.fits, results/sofia_pbc/hcg30/hcg30_line60_masked.pb_corr_vopt_cubelets/hcg30_line60_masked.pb_corr_vopt_1_snr.fits
    output: results/publication/figures/ngc1622_mom0.pdf
    jobid: 4
    reason: Set of input files has changed since last execution; Code has changed since last execution
    resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=/tmp

RuleException in rule plot_sofia_products in file /data/workflow/rules/plot_sofia_products.smk, line 1:
NameError: The name 'ngc1622_snr' is unknown in this context. Please make sure that you defined that variable. Also note that braces not used for variable access have to be escaped by repeating them, i.e. {{print $1}}, when formatting the following:
python workflow/scripts/plot_sofia_products.py --gfilter {input.ngc1622_g} --rfilter {input.ngc1622_r} --ifilter {input.ngc1622_i} --contour_file {input.ngc1622_mom0} --source_id {params.source_id} --input_fits {ngc1622_snr}
